spring:
  application:
    name: Financial System

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.4.70:3306/financial?createDatabaseIfNotExist=true
    username: root
    password: Stonesour25!

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

vaadin:
  launch-browser= true: