spring:
  datasource:
    url: ${SPRING_DB_URL}
    username: ${SPRING_DB_USER}
    password: ${SPRING_DB_PASSWORD}
    driver-class-name: ${SPRING_DB_DRIVE:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        default_schema: ${SPRING_DB_SCHEMA:public}
  data:
    rest:
      base-path: /data
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    cache: false
server:
  port: 666
